# Generated by Django 2.1 on 2020-08-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=140)),
                ('genre', models.CharField(max_length=140)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
